language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - cargo test --release  # We test only in release mode because of the ET 0.0 seconds bug
