[package]
name = "hifitime"
version = "1.0.5"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "Precise date and time handling in Rust built on top of std::f64 with leap second support"
homepage = "https://github.com/ChristopherRabotin/hifitime"
documentation = "https://docs.rs/hifitime/"
repository = "https://github.com/ChristopherRabotin/hifitime"
keywords = ["date", "time", "barycentric", "leap-second", "tai"]
categories = ["date-and-time"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
rand = { version = "0.7", optional = true }
rand_distr = { version = "0.2", optional = true }

[features]
default = []
simulation = ["rand", "rand_distr"]
